name: RGB.NET-Release

on:
  push:
    branches: [ aytackydln-temp-fork ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Add Github Packages source
        run: dotnet nuget add source --username ${{ GITHUB_REPOSITORY_OWNER }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ GITHUB_REPOSITORY_OWNER }}/index.json"

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release /p:Version=${{ steps.versioning.outputs.version }}
      - name: Nuget Push
        run: dotnet nuget push bin\*.nupkg --skip-duplicate --source "github"
